[package]
name = "fuzz"
version = "0.1.0"
authors = ["Seb Glazebrook <sebastian.glazebrook@redbubble.com>"]

[dependencies]

ncurses = "*"
crossbeam = "*"

[dependencies.directory_filter]
git = "http://github.com/sebglazebrook/directory_filter.git"
rev = "55513d4"
